import pytest

SERVER_PROFILES = {
    "polis": {
        "base_url": "https://pol.is",
        "conversation_id": "2demo",
        "report_id": "r49xtpmxk2mjmkpyhwuau",
        "expected_data": {
            "2demo": {
                "first_comment": {
                    'conversation_id': '2demo',
                    'txt': 'This is a game changer. The myriad of unintended consequences it too complex to really understand; even for restaurant veterans.\n',
                    'tid': 1,
                    'created':
                    '1403054218578',
                    'quote_src_url': None,
                    'is_seed': False,
                    'is_meta': False,
                    'lang': 'en',
                    'pid': 0,
                    'velocity': 1,
                    'mod': 1,
                    'active': True,
                    'agree_count': 86,
                    'disagree_count': 38,
                    'pass_count': 44,
                    'count': 168,
                },
                "conversation": {
                    'auth_needed_to_vote': False,
                    'auth_needed_to_write': True,
                    'auth_opt_allow_3rdparty': True,
                    'auth_opt_fb': True,
                    'auth_opt_tw': True,
                    'bgcolor': None,
                    'context': 'polis_test',
                    'conversation_id': '2demo',
                    'course_id': None,
                    'dataset_explanation': None,
                    'description': 'How do you think the new minimum wage law will affect Seattle? Will it be for the better or for the worse? Why?',
                    'email_domain': None,
                    'help_bgcolor': None,
                    'help_color': None,
                    'help_type': 1,
                    'importance_enabled': False,
                    'is_active': True,
                    'is_anon': False,
                    'is_curated': False,
                    'is_data_open': True,
                    'is_draft': False,
                    'is_mod': False,
                    'is_owner': False,
                    'is_public': True,
                    'link_url': None,
                    'need_suzinvite': False,
                    'org_id': 125,
                    'owner': 125,
                    'owner_sees_participation_stats': False,
                    'ownername': 'Mike Bjorkegren',
                    'parent_url': None,
                    'participant_count': 6361,
                    'prioritize_seed': False,
                    'profanity_filter': True,
                    'site_id': 'polis_site_id_mike_all2',
                    'socialbtn_type': 1,
                    'spam_filter': True,
                    'strict_moderation': True,
                    'style_btn': '',
                    'subscribe_type': 1,
                    'topic': '$15/hour',
                    'translations': [],
                    'treevite_enabled': False,
                    'upvotes': 1,
                    'use_xid_whitelist': False,
                    'vis_type': 1,
                    'write_hint_type': 1,
                    'write_type': 1,
                    'created': '1403054152585',
                    'modified': '1764981306417000',
                },
                "first_vote": {
                    'pid': 0,
                    'tid': 0,
                    'vote': 0,
                    'weight_x_32767': 0,
                    'modified': '1403054214196',
                    'conversation_id': '2demo',
                },
            },
            "r49xtpmxk2mjmkpyhwuau": {
                "report": {
                    "report_id": "r49xtpmxk2mjmkpyhwuau",
                    "created": "1501757120502",
                    "modified": "1501757120502",
                    "label_x_neg": None,
                    "label_y_neg": None,
                    "label_y_pos": None,
                    "label_x_pos": None,
                    "label_group_0": None,
                    "label_group_1": None,
                    "label_group_2": None,
                    "label_group_3": None,
                    "label_group_4": None,
                    "label_group_5": None,
                    "label_group_6": None,
                    "label_group_7": None,
                    "label_group_8": None,
                    "label_group_9": None,
                    "report_name": None,
                    "mod_level": -2,
                    "conversation_id": "5psrv8bm2a"
                },
            },
        },
    },
    "voxit": {
        "base_url": "https://voxit.sitra.fi",
        "conversation_id": "2rvpbfm2fc",
        "report_id": "r8m3werjkdhdpejy3awz7",
        "expected_data": {
            "2rvpbfm2fc": {
                "first_comment": {
                    "txt": "Jag tucker det inte påverkar min vardag så himla mycket men om det var ett problem ser jag inte det som ett hot",
                    "tid": 111,
                    "created": "1744797207745",
                    "quote_src_url": None,
                    "is_seed": False,
                    "is_meta": False,
                    "lang": "sv",
                    "pid": 69,
                    "velocity": 1,
                    "mod": -1,
                    "active": False,
                    "agree_count": 1,
                    "disagree_count": 0,
                    "pass_count": 0,
                    "count": 1,
                    "conversation_id": "2rvpbfm2fc"
                },
                "conversation": {
                    "topic": "Mitä sinä ajattelet turvallisuudesta? / Vad tycker du om säkerheten?",
                    "description": "Turvallisuus on jokaisen lapsen ja nuoren perusoikeus. Hyvä helsinkiläinen nuori, mitä asioita kotikaupungissasi voitaisiin tehdä, jotta tunnet olosi turvalliseksi? Mikä turvallisuudentunnettasi nykyisin heikentää? Mitä toivoisit Suomen tai maailman päättäjien tekevän?\n\nSäkerhet är en grundläggande rättighet för varje barn och ungdom. Kära unga Helsingforsbo, vad kan göras i din hemstad för att du ska känna dig trygg? Vad försvagar din känsla av trygghet just nu? Vad skulle du önska att beslutsfattare i Finland eller världen skulle göra?",
                    "link_url": None,
                    "parent_url": None,
                    "upvotes": 1,
                    "participant_count": 167,
                    "is_anon": False,
                    "is_active": True,
                    "is_draft": True,
                    "is_public": True,
                    "is_data_open": False,
                    "profanity_filter": True,
                    "spam_filter": True,
                    "strict_moderation": True,
                    "prioritize_seed": False,
                    "vis_type": 1,
                    "write_type": 0,
                    "help_type": 1,
                    "write_hint_type": 1,
                    "style_btn": None,
                    "socialbtn_type": 0,
                    "subscribe_type": 0,
                    "branding_type": 1,
                    "bgcolor": None,
                    "help_bgcolor": None,
                    "help_color": None,
                    "email_domain": None,
                    "use_xid_whitelist": False,
                    "owner": 131,
                    "org_id": 131,
                    "context": None,
                    "course_id": None,
                    "lti_users_only": False,
                    "owner_sees_participation_stats": False,
                    "auth_needed_to_vote": False,
                    "auth_needed_to_write": False,
                    "auth_opt_fb": False,
                    "auth_opt_tw": False,
                    "auth_opt_allow_3rdparty": False,
                    "is_slack": False,
                    "modified": "1756119606942",
                    "created": "1744202190861",
                    "importance_enabled": False,
                    "site_id": "polis_site_id_p0mCYtxi5Imtv1eofK",
                    "translations": [],
                    "ownername": "polis-sitra",
                    "is_mod": False,
                    "is_owner": False,
                    "conversation_id": "2rvpbfm2fc",
                },
                "first_vote": {
                    "conversation_id": "2rvpbfm2fc",
                    "modified": "1744286030088",
                    "pid": 0,
                    "tid": 0,
                    "vote": 0,
                    "weight_x_32767": 0,
                },
            },
            "r8m3werjkdhdpejy3awz7": {
                "report": {
                    "report_id": "r8m3werjkdhdpejy3awz7",
                    "created": "1744285985810",
                    "modified": "1744285985810",
                    "report_name": None,
                    "label_x_neg": None,
                    "label_x_pos": None,
                    "label_y_neg": None,
                    "label_y_pos": None,
                    "label_group_0": None,
                    "label_group_1": None,
                    "label_group_2": None,
                    "label_group_3": None,
                    "label_group_4": None,
                    "label_group_5": None,
                    "label_group_6": None,
                    "label_group_7": None,
                    "label_group_8": None,
                    "label_group_9": None,
                    "conversation_id": "2rvpbfm2fc",
                },
            }
        },
    },
}


@pytest.fixture(params=[pytest.param(name, id=name) for name in SERVER_PROFILES])
def server_profile(request):
    """Runs each test once per server profile."""
    profile = SERVER_PROFILES[request.param]
    profile["name"] = request.param
    return profile


@pytest.fixture
def client(server_profile):
    from polis_client.client4 import PolisClient
    return PolisClient(base_url=server_profile["base_url"])